MEASURE _measures[метаданные время обновления база] = MAX('метаданные'[время обновления база])
MEASURE _measures[метаданные время обновления модель] = MAX('метаданные'[время обновления модель])
MEASURE _measures[метаданные время обновления модель] = MAX('метаданные'[время обновления модель])
MEASURE _measures[метаданные дата модель] = //для отчета PBI
	IF(
		HASONEVALUE('проект'[проект краткий]);
		MAX('факт'[дата модель])
	)
MEASURE _measures[метаданные проект] = SELECTEDVALUE('проект'[проект краткий]) //для отчета PBI
MEASURE _measures[метаданные заголовок показатели проекта] = //для отчета PBI
	"Фактические объемы, трудозатраты и нормы по проекту " & [метаданные проект] & " на "  & 
        FORMAT([метаданные дата модель]; "mmmm yyyy")
        

