MEASURE _measures[контракт норма типовые] = DIVIDE([контракт нормочасы]; [контракт объем типовые])
MEASURE _measures[контракт норма по факту типовые] = DIVIDE([факт нормочасы]; [факт объем типовые])
MEASURE _measures[контракт норма по факту зимний типовые] = DIVIDE([факт нормочасы зимний]; [факт объем типовые])
MEASURE _measures[факт норма типовые] = DIVIDE([факт часы]; [факт объем типовые])
MEASURE _measures[факт + доп норма типовые] = DIVIDE([факт + доп часы]; [факт объем типовые])
MEASURE _measures[ключевые норма типовые] = DIVIDE([ключевые часы]; [ключевые объем типовые])