MEASURE _measures[выбор мер] = 
	VAR _selected_measure = SELECTEDVALUE('меры названия'[мера])
    VAR _result = 
        SWITCH(
            _selected_measure;
            "контракт объем типовые"; 
                IF(NOT(ISBLANK([контракт объем типовые]));FORMAT([контракт объем типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "контракт нормочасы"; 
                IF(NOT(ISBLANK([контракт нормочасы]));FORMAT([контракт нормочасы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт нормочасы % контракт"; 
                IF(NOT(ISBLANK([факт нормочасы % контракт]));FORMAT([факт нормочасы % контракт]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            --"_blank_1"; 
            --    IF(NOT(ISBLANK([_blank_1]));FORMAT([_blank_1]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт объем типовые"; 
                IF(NOT(ISBLANK([факт объем типовые]));FORMAT([факт объем типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "ключевые объем типовые"; 
                IF(NOT(ISBLANK([ключевые объем типовые]));FORMAT([ключевые объем типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта ключевые объемы % факт"; 
                IF(NOT(ISBLANK([дельта ключевые объемы % факт]));FORMAT([дельта ключевые объемы % факт]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            --"_blank_2"; 
            --    IF(NOT(ISBLANK([_blank_2]));FORMAT([_blank_2]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт нормочасы"; 
                IF(NOT(ISBLANK([факт нормочасы]));FORMAT([факт нормочасы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт нормочасы зимний"; 
                IF(NOT(ISBLANK([факт нормочасы зимний]));FORMAT([факт нормочасы зимний]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт часы"; 
                IF(NOT(ISBLANK([факт часы]));FORMAT([факт часы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            --"факт часы % уровень"; 
            --    IF(NOT(ISBLANK([факт часы % уровень]));FORMAT([факт часы % уровень]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "ключевые часы"; 
                IF(NOT(ISBLANK([ключевые часы]));FORMAT([ключевые часы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта ключевые часы % факт + доп"; 
                IF(NOT(ISBLANK([дельта ключевые часы % факт + доп]));FORMAT([дельта ключевые часы % факт + доп]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "доп часы"; 
                IF(NOT(ISBLANK([доп часы]));FORMAT([доп часы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "доп часы % факт"; 
                IF(NOT(ISBLANK([доп часы % факт]));FORMAT([доп часы % факт]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт + доп часы"; 
                IF(NOT(ISBLANK([факт + доп часы]));FORMAT([факт + доп часы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта факт часы % нормочасы"; 
                IF(NOT(ISBLANK([дельта факт часы % нормочасы]));FORMAT([дельта факт часы % нормочасы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта факт часы % нормочасы зимний"; 
                IF(NOT(ISBLANK([дельта факт часы % нормочасы зимний]));FORMAT([дельта факт часы % нормочасы зимний]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта факт часы + доп % нормочасы"; 
                IF(NOT(ISBLANK([дельта факт часы + доп % нормочасы]));FORMAT([дельта факт часы + доп % нормочасы]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "дельта факт часы + доп % нормочасы зимний"; 
                IF(NOT(ISBLANK([дельта факт часы + доп % нормочасы зимний]));FORMAT([дельта факт часы + доп % нормочасы зимний]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт часы техника"; 
                IF(NOT(ISBLANK([факт часы техника]));FORMAT([факт часы техника]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            --"_blank_3"; 
            --    IF(NOT(ISBLANK([_blank_3]));FORMAT([_blank_3]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "контракт норма типовые"; 
                IF(NOT(ISBLANK([контракт норма типовые]));FORMAT([контракт норма типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "контракт норма по факту типовые"; 
                IF(NOT(ISBLANK([контракт норма по факту типовые]));FORMAT([контракт норма по факту типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "контракт норма по факту зимний типовые"; 
                IF(NOT(ISBLANK([контракт норма по факту зимний типовые]));FORMAT([контракт норма по факту зимний типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт норма типовые"; 
                IF(NOT(ISBLANK([факт норма типовые]));FORMAT([факт норма типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "факт + доп норма типовые"; 
                IF(NOT(ISBLANK([факт + доп норма типовые]));FORMAT([факт + доп норма типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")));
            "ключевые норма типовые"; 
                IF(NOT(ISBLANK([ключевые норма типовые]));FORMAT([ключевые норма типовые]; SELECTEDVALUE('меры названия'[мера формат]; "#,##0")))
        )
    RETURN _result

MEASURE _measures[переключатель мер усл формат] = 
    VAR _selected_measure = SELECTEDVALUE('меры'[мера])
    VAR _result = 
		SWITCH(
			_selected_measure;
			"контракт нормочасы"; [контракт нормочасы];
			"факт нормочасы"; [факт нормочасы];
			"факт нормочасы % контракт"; [факт нормочасы % контракт]
 		)
	RETURN _result